name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  install_and_test:
    name: Install project and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: " 3.13.0-alpha.3"

      - name: "Install project on ${{ matrix.os }}"
        run: |
          pip install .

      - name: Run tests on ${{ matrix.os }}
        run: |
          python tests/test_audioop.py

  build_wheels:
    if: github.event_name == 'push'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [install_and_test]
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: "cp313-*"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
